### ISSUE TITLE
按你的说明，跑起来报错了

### ISSUE THREAD

**Issue by hugoren** [childe/esproxy#1]
/Users/hugo/devops/sso/esproxy/esproxy/urls.py:17: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got esproxy.views.home). Pass the callable instead.
  url(r'^$', 'esproxy.views.home'),

**Comment by childe** [comment]
这只是个warning吧, 我是用django 1.8跑的.
