### ISSUE TITLE
请问该项目是对版本的要求写死了吗

### ISSUE THREAD

**Issue by hugoren** [childe/esproxy#2]
Django==1.8.3
PyYAML==3.11
uWSGI==2.0.9
wheel==0.24.0
Status API Training Shop Blog About Pricing

我用的其它版本，可提示一定要用这些版本？

**Comment by childe** [comment]
其他版本我没有测试过, 只知道django1.7是可以的.
强烈建议用virtualenv.

**Comment by hugoren** [comment]
谢谢
