### ISSUE TITLE
有两个问题没懂？

### ISSUE THREAD

**Issue by hugoren** [childe/esproxy#3]
1.cas，你已经当成一个应用写在项目esproxy里了

**Comment by childe** [comment]
1. django_cas是一个独立的模块, 如果需要接入cas sso, 就找教程配置一下, 不需要就不用配置CAS.
2. 没域名分组的权限? 没太明白, 感觉不难吧.

**Comment by hugoren** [comment]
谢谢，加入了cas,访问时候跳到cas.corp.com
